AppsFlyerKnowledge/devhub

- docs/guides/deep_linking/smart-banner-web-tool/dl_smart_banner_migration_guide.md
@liaz-af 
Added a deprecation note to v1.
Please review.
> dl_sb_migration: Added deprecation notice

- docs/guides/sdks/getting-started/sdk-integration.md
@liaz-af Added HTML for the react box
> getting started-integration: Added React Native box.

- docs/guides/sdks/android-sdk/integrate-android-sdk.md
@liaz-af: added log session section for Android. The other PR is for iOS.
> integrate-android: added log session section

- docs/guides/sdks/ios-sdk/integrate-ios-sdk.md
@liaz-af Added a new log session section.
> iOS integration: Adding log session section

- docs/apis/mos/pushapi_config_api.yaml
closes [DELIVERY-35179](https://appsflyer.atlassian.net/browse/DELIVERY-35179)
> [DELIVERY-35179] add Push-API authentication tokens swagger

- docs/guides/deep_linking/dl_android_overview/dl_android_init_setup.md
- docs/guides/deep_linking/dl_ios_overview/dl_ios_init_setup.md
@liaz-af, there are 2 files in the branch because it's the same subject from the KB request.
> Android and iOS OneLink init - Fix note about universal linking

- docs/guides/sdks/android-sdk/install-android-sdk.md
@liaz-af Added limitation per [this Jira ticket](https://appsflyer.atlassian.net/browse/DELIVERY-34825)
> Install Android SDK - Added limitation: Boot Complete

- docs/guides/sdks/android-sdk/send-consent-dma-android.md
- docs/guides/sdks/ios-sdk/send-consent-dma-ios.md
> DMA - Review testing sections

- docs/guides/sdks/android-sdk/android_release_notes_md.md
- docs/guides/sdks/ios-sdk/ios_release_notes_md.md
Release Notes for v6.13.0. Please review. Thanks!
> updated release notes for v6.13.0 on Android and iOS

- docs/guides/deep_linking/smart-script-web-tool/dl_smart_script_v2.md
> Smart Script v2.0 - add local storage use case

- docs/guides/sdks/android-sdk/install-android-sdk.md
@liaz-af Pls. review and approve.
> Android Install: Added Meta Install Referrer

- docs/guides/sdks/ios-sdk/install-ios-sdk.md
@liaz-af: according to this [KB request](https://appsflyer.slack.com/archives/C5RDRS58X/p1711553716695329)
> iOS-install - added GitHub SPM libraries links

- docs/guides/sdks/ios-sdk/integrate-ios-sdk.md
@liaz-af KB request: https://appsflyer.slack.com/archives/C5RDRS58X/p1711604120046939
> Integrate iOS SDK - added note about CUID

- docs/guides/sdks/android-sdk-reference/android-sdk-reference-appsflyerlib.md
- docs/guides/sdks/ios-sdk-reference/ios-sdk-reference-appsflyerlib.md
@liaz-af Per [kb-request](https://appsflyer.slack.com/archives/C5RDRS58X/p1712467533128859)
> appsFlyerLib - added enableTCFDataCollection

- docs/apis/mobile/test_console_api.yaml
> Test console API - proofing

- site-config/globalStyle.css
- site-config/hc.readme.io/customJavaScript.js
- global style sheet with the updated CSS
- updated the global JS file
> added api categories

- docs/guides/sdks/android-sdk/install-android-sdk.md
@liaz-af : [Slack](https://appsflyer.slack.com/archives/C5RDRS58X/p1717417451602109):
> Install SDK - Added backup rules section

- docs/apis/OneLink/onelinkapi_overview.md
> API overview - onelinkapi

- docs/apis/rta/s2s_events_api3.yaml
@liaz-af Per Slack https://appsflyer.slack.com/archives/C07GVEKFL6A/p1724022638898479
> Send Events API - Softer note

- docs/guides/sdks/android-sdk/install-android-sdk.md
- docs/guides/sdks/android-sdk/oaid.md
@liaz-af: Per KBR: https://appsflyer.slack.com/archives/C5RDRS58X/p1728915204838979
> Add Proguard instructions to OAID and Huawei referrer

- docs/guides/sdks/android-sdk/testing-android.md
- docs/guides/sdks/ios-sdk/testing-ios.md
@liaz-af KB request: https://appsflyer.slack.com/archives/C7JDU34V9/p1731311119403269?thread_ts=1729143155.570689&cid=C7JDU34V9
> Testing-android-ios troubleshoot low TLS

- docs/guides/sdks/android-sdk-reference/android-sdk-reference-appsflyerconsent.md
- docs/guides/sdks/android-sdk/send-consent-dma-android.md
- docs/guides/sdks/ios-sdk-reference/ios-sdk-reference-appsflyerconsent.md
- docs/guides/sdks/ios-sdk/send-consent-dma-ios.md
> DMA 2.0 - New AF consent version

- docs/apis/OneLink/onelinkapi.yml
@liaz-af KB request: https://appsflyer.slack.com/archives/C5RDRS58X/p1741870963922219
> OneLinkapi.yml - changed to V2 token

- docs/guides/sdks/ios-sdk/purchase-connector-ios.md
@liaz-af Please approve this new addition from Michael Talapov
> purchase-connector-ios - New receipt validation api

- docs/guides/sdks/android-sdk-reference/android-sdk-reference-appsflyerlib.md
- docs/guides/sdks/android-sdk/validate-and-log-purchase-android.md
- docs/guides/sdks/ios-sdk-reference/ios-sdk-reference-appsflyerlib.md
- docs/guides/sdks/ios-sdk/validate-and-log-purchase-ios.md
@liaz-af Please review and approve.
> Validate and log purchase update iOS and Android
